# -*- coding: utf-8 -*-
from __future__ import print_function
from requests import Session

empty_urls = {
    'primera division de costa rica': 'http://www.espn.in/soccer/table/_/league/crc.1',
    'jamaica premier league': 'http://www.espn.in/soccer/table/_/league/jam.1',
    'caf champions league': 'http://www.espn.in/soccer/table/_/league/caf.champions',
}




cups_urls = {
    'fifa world cup': 'http://www.espn.in/soccer/table/_/league/fifa.world',
    'ucl': 'http://www.espn.in/football/table/_/league/uefa.champions',
    'europa': 'http://www.espn.in/football/table/_/league/uefa.europa',
    'efl trophy': 'http://www.espn.in/soccer/table/_/league/eng.trophy',
    'scotland league cup': 'http://www.espn.in/soccer/table/_/league/sco.cis',
    'fifa confederations cup': 'http://www.espn.in/soccer/table/_/league/fifa.confederations',
    'mens olympic tournament': 'http://www.espn.in/soccer/table/_/league/fifa.olympics',
    'u-20 world cup': 'http://www.espn.in/soccer/table/_/league/fifa.world.u20',
    'u-17 world cup': 'http://www.espn.in/soccer/table/_/league/fifa.world.u17',
    'euro': 'http://www.espn.in/soccer/table/_/league/uefa.euro',
    'concacaf gold cup': 'http://www.espn.in/soccer/table/_/league/concacaf.gold',
    'copa america': 'http://www.espn.in/soccer/table/_/league/conmebol.america',
    'africa cup of nations': 'http://www.espn.in/soccer/table/_/league/caf.nations',
    'african nations championship': 'http://www.espn.in/soccer/table/_/league/caf.championship',
    'afc asian cup': 'http://www.espn.in/soccer/table/_/league/afc.cup',
    'afc asian cup qualifiers': 'http://www.espn.in/soccer/table/_/league/afc.cupq',
    'aff cup': 'http://www.espn.in/soccer/table/_/league/aff.championship',
    'womens world cup': 'http://www.espn.in/soccer/table/_/league/fifa.wwc',
    'womens olympic tournament': 'http://www.espn.in/soccer/table/_/league/fifa.w.olympics',
    "uefa women's champions league": 'http://www.espn.in/soccer/table/_/league/uefa.weuro',
    'copa libertadores': 'http://www.espn.in/soccer/table/_/league/conmebol.libertadores',
    'brazil serie c': 'http://www.espn.in/soccer/table/_/league/bra.3',
    'brazil: campeonato paulista': 'http://www.espn.in/soccer/table/_/league/bra.camp.paulista',
    'colombia segunda division': 'http://www.espn.in/soccer/table/_/league/col.2',
    'concacaf champions league': 'http://www.espn.in/soccer/table/_/league/concacaf.champions',
    'afc champions league': 'http://www.espn.in/soccer/table/_/league/afc.champions',
    'caf confederation cup': 'http://www.espn.in/soccer/table/_/league/caf.confed',
    'major league soccer': 'http://www.espn.in/soccer/table/_/league/usa.1',
    'united soccer league': 'http://www.espn.in/soccer/table/_/league/usa.usl.1',

}


leagues_urls = {
    'epl': 'http://www.espn.in/football/table/_/league/eng.1',
    'english championship': 'http://www.espn.in/soccer/table/_/league/eng.2',
    'laliga': 'http://www.espn.in/football/table/_/league/esp.1',
    'indian super league': 'http://www.espn.in/football/table/_/league/ind.1',
    'serie a': 'http://www.espn.in/football/table/_/league/ita.1',
    'bundesliga': 'http://www.espn.in/football/table/_/league/ger.1',
    'ligue 1': 'http://www.espn.in/football/table/_/league/fra.1',
    'italian serie b': 'http://www.espn.in/football/table/_/league/ita.2',
    'england league two': "http://www.espn.in/football/table/_/league/eng.4",
    'english league one': "http://www.espn.in/football/table/_/league/eng.3",
    'portuguese liga': "http://www.espn.in/football/table/_/league/por.1",
    u'spanish segunda división': "http://www.espn.in/football/table/_/league/esp.2",
    'belgian jupiler league': 'http://www.espn.in/football/table/_/seasontype/1/league/bel.1',
    'english national league': 'http://www.espn.in/football/table/_/league/eng.5',
    'russian premier league': 'http://www.espn.in/football/table/_/league/rus.1',
    'chinese super league': 'http://www.espn.in/football/table/_/league/chn.1',
    'german 2. bundesliga': 'http://www.espn.in/football/table/_/league/ger.2',
    'mexican liga mx': 'http://www.espn.in/soccer/table/_/league/mex.1',
    'ascenso mx': 'http://www.espn.in/soccer/table/_/league/mex.2',
    'scottish premiership': 'http://www.espn.in/soccer/table/_/league/sco.1',
    'scottish championship': 'http://www.espn.in/soccer/table/_/league/sco.2',
    'scottish league one': 'http://www.espn.in/soccer/table/_/league/sco.3',
    'scottish league two': 'http://www.espn.in/soccer/table/_/league/sco.4',
    'welsh premier league': 'http://www.espn.in/soccer/table/_/league/wal.1',
    'northern irish premiership': 'http://www.espn.in/soccer/table/_/league/nir.1',
    'ireland premier division': 'http://www.espn.in/soccer/table/_/league/irl.1',
    'dutch eredivisie': 'http://www.espn.in/soccer/table/_/league/ned.1',
    'turkish super lig': 'http://www.espn.in/soccer/table/_/league/tur.1',
    'superleague greece': 'http://www.espn.in/soccer/table/_/league/gre.1',
    'austrian bundesliga': 'http://www.espn.in/soccer/table/_/league/aut.1',
    'swiss super league': 'http://www.espn.in/soccer/table/_/league/sui.1',
    'danish sas-ligaen': 'http://www.espn.in/soccer/table/_/league/den.1',
    'norwegian eliteserien': 'http://www.espn.in/soccer/table/_/league/nor.1',
    'swedish allsvenskanliga': 'http://www.espn.in/soccer/table/_/league/swe.1',
    'romanian first division': 'http://www.espn.in/soccer/table/_/league/rou.1',
    'israeli premier league': 'http://www.espn.in/soccer/table/_/league/isr.1',
    'maltese premier league': 'http://www.espn.in/soccer/table/_/league/mlt.1',
    'french ligue 2': 'http://www.espn.in/soccer/table/_/league/fra.2',
    'dutch eerste divisie': 'http://www.espn.in/soccer/table/_/league/ned.2',
    u'primera división de argentina': 'http://www.espn.in/soccer/table/_/league/arg.1',
    'nacional b de argentina': 'http://www.espn.in/soccer/table/_/league/arg.2',
    'primera division b de argentina': 'http://www.espn.in/soccer/table/_/league/arg.3',
    'argentina primera c metropolitana': 'http://www.espn.in/soccer/table/_/league/arg.4',
    'primera division d de argentina': 'http://www.espn.in/soccer/table/_/league/arg.5',
    'brazil serie a': 'http://www.espn.in/soccer/table/_/league/bra.1',
    'brazil serie b': 'http://www.espn.in/soccer/table/_/league/bra.2',
    'brazil campeonato mineiro': 'http://www.espn.in/soccer/table/_/league/bra.camp.mineiro',
    'brazil: campeonato gaucho': 'http://www.espn.in/soccer/table/_/league/bra.camp.gaucho',
    u'fútbol profesional colombiano': 'http://www.espn.in/soccer/table/_/league/col.1',
    'primera division de chile': 'http://www.espn.in/soccer/table/_/league/chi.1',
    'ecuador serie a': 'http://www.espn.in/soccer/table/_/league/ecu.1',
    'primera division de paraguay': 'http://www.espn.in/soccer/table/_/league/par.1',
    'primera division de uruguay': 'http://www.espn.in/soccer/table/_/league/uru.1',
    'primera profesional de peru': 'http://www.espn.in/soccer/table/_/league/per.1',
    'primera division venezuela': 'http://www.espn.in/soccer/table/_/league/ven.1',
    'bolivia liga de futbol': 'http://www.espn.in/soccer/table/_/league/bol.1',
    'guatemala primera division': 'http://www.espn.in/soccer/table/_/league/gua.1',
    'primera division de honduras': 'http://www.espn.in/soccer/table/_/league/hon.1',
    u'primera división de el salvador': 'http://www.espn.in/soccer/table/_/league/slv.1',
    'north american soccer league': 'http://www.espn.in/soccer/table/_/league/usa.nasl',
    'nwsl womens league': 'http://www.espn.in/soccer/table/_/league/usa.nwsl',
    'australian a-league': 'http://www.espn.in/soccer/table/_/league/aus.1',
    'japanese j league': 'http://www.espn.in/soccer/table/_/league/jpn.1',
    'indonesia liga 1': 'http://www.espn.in/soccer/table/_/league/idn.1',
    'malaysian super league': 'http://www.espn.in/soccer/table/_/league/mys.1',
    'singapore s-league': 'http://www.espn.in/soccer/table/_/league/sgp.1',
    'thai premier league': 'http://www.espn.in/soccer/table/_/league/tha.1',
    'south african premiership': 'http://www.espn.in/soccer/table/_/league/rsa.1',
    'south african national first division': 'http://www.espn.in/soccer/table/_/league/rsa.2',
    'nigeria professional league': 'http://www.espn.in/soccer/table/_/league/nga.1',
    'ghana premier league': 'http://www.espn.in/soccer/table/_/league/gha.1',
    'kenyan premier league': 'http://www.espn.in/soccer/table/_/league/ken.1',
    'uganda super league': 'http://www.espn.in/soccer/table/_/league/uga.1',
    'zambian league': 'http://www.espn.in/soccer/table/_/league/zam.1',
    'premier soccer league': 'http://www.espn.in/soccer/table/_/league/zim.1',
    'brazilian campeonato carioca': 'http://www.espn.in/soccer/table/_/league/bra.camp.carioca'
}



urls={

'fifa world cup': 'http://www.espn.in/soccer/table/_/league/fifa.world',
    'ucl': 'http://www.espn.in/football/table/_/league/uefa.champions',
    'europa': 'http://www.espn.in/football/table/_/league/uefa.europa',
    'efl trophy': 'http://www.espn.in/soccer/table/_/league/eng.trophy',
    'scotland league cup': 'http://www.espn.in/soccer/table/_/league/sco.cis',
    'fifa confederations cup': 'http://www.espn.in/soccer/table/_/league/fifa.confederations',
    'mens olympic tournament': 'http://www.espn.in/soccer/table/_/league/fifa.olympics',
    'u-20 world cup': 'http://www.espn.in/soccer/table/_/league/fifa.world.u20',
    'u-17 world cup': 'http://www.espn.in/soccer/table/_/league/fifa.world.u17',
    'euro': 'http://www.espn.in/soccer/table/_/league/uefa.euro',
    'concacaf gold cup': 'http://www.espn.in/soccer/table/_/league/concacaf.gold',
    'copa america': 'http://www.espn.in/soccer/table/_/league/conmebol.america',
    'africa cup of nations': 'http://www.espn.in/soccer/table/_/league/caf.nations',
    'african nations championship': 'http://www.espn.in/soccer/table/_/league/caf.championship',
    'afc asian cup': 'http://www.espn.in/soccer/table/_/league/afc.cup',
    'afc asian cup qualifiers': 'http://www.espn.in/soccer/table/_/league/afc.cupq',
    'aff cup': 'http://www.espn.in/soccer/table/_/league/aff.championship',
    'womens world cup': 'http://www.espn.in/soccer/table/_/league/fifa.wwc',
    'womens olympic tournament': 'http://www.espn.in/soccer/table/_/league/fifa.w.olympics',
    "uefa women's champions league": 'http://www.espn.in/soccer/table/_/league/uefa.weuro',
    'copa libertadores': 'http://www.espn.in/soccer/table/_/league/conmebol.libertadores',
    'brazil serie c': 'http://www.espn.in/soccer/table/_/league/bra.3',
    'brazil: campeonato paulista': 'http://www.espn.in/soccer/table/_/league/bra.camp.paulista',
    'colombia segunda division': 'http://www.espn.in/soccer/table/_/league/col.2',
    'concacaf champions league': 'http://www.espn.in/soccer/table/_/league/concacaf.champions',
    'afc champions league': 'http://www.espn.in/soccer/table/_/league/afc.champions',
    'caf confederation cup': 'http://www.espn.in/soccer/table/_/league/caf.confed',
    'major league soccer': 'http://www.espn.in/soccer/table/_/league/usa.1',
    'united soccer league': 'http://www.espn.in/soccer/table/_/league/usa.usl.1',
    'epl': 'http://www.espn.in/football/table/_/league/eng.1',
    'english championship': 'http://www.espn.in/soccer/table/_/league/eng.2',
    'laliga': 'http://www.espn.in/football/table/_/league/esp.1',
    'indian super league': 'http://www.espn.in/football/table/_/league/ind.1',
    'serie a': 'http://www.espn.in/football/table/_/league/ita.1',
    'bundesliga': 'http://www.espn.in/football/table/_/league/ger.1',
    'ligue 1': 'http://www.espn.in/football/table/_/league/fra.1',
    'italian serie b': 'http://www.espn.in/football/table/_/league/ita.2',
    'england league two': "http://www.espn.in/football/table/_/league/eng.4",
    'english league one': "http://www.espn.in/football/table/_/league/eng.3",
    'portuguese liga': "http://www.espn.in/football/table/_/league/por.1",
    u'spanish segunda división': "http://www.espn.in/football/table/_/league/esp.2",
    'belgian jupiler league': 'http://www.espn.in/football/table/_/seasontype/1/league/bel.1',
    'english national league': 'http://www.espn.in/football/table/_/league/eng.5',
    'russian premier league': 'http://www.espn.in/football/table/_/league/rus.1',
    'chinese super league': 'http://www.espn.in/football/table/_/league/chn.1',
    'german 2. bundesliga': 'http://www.espn.in/football/table/_/league/ger.2',
    'mexican liga mx': 'http://www.espn.in/soccer/table/_/league/mex.1',
    'ascenso mx': 'http://www.espn.in/soccer/table/_/league/mex.2',
    'scottish premiership': 'http://www.espn.in/soccer/table/_/league/sco.1',
    'scottish championship': 'http://www.espn.in/soccer/table/_/league/sco.2',
    'scottish league one': 'http://www.espn.in/soccer/table/_/league/sco.3',
    'scottish league two': 'http://www.espn.in/soccer/table/_/league/sco.4',
    'welsh premier league': 'http://www.espn.in/soccer/table/_/league/wal.1',
    'northern irish premiership': 'http://www.espn.in/soccer/table/_/league/nir.1',
    'ireland premier division': 'http://www.espn.in/soccer/table/_/league/irl.1',
    'dutch eredivisie': 'http://www.espn.in/soccer/table/_/league/ned.1',
    'turkish super lig': 'http://www.espn.in/soccer/table/_/league/tur.1',
    'superleague greece': 'http://www.espn.in/soccer/table/_/league/gre.1',
    'austrian bundesliga': 'http://www.espn.in/soccer/table/_/league/aut.1',
    'swiss super league': 'http://www.espn.in/soccer/table/_/league/sui.1',
    'danish sas-ligaen': 'http://www.espn.in/soccer/table/_/league/den.1',
    'norwegian eliteserien': 'http://www.espn.in/soccer/table/_/league/nor.1',
    'swedish allsvenskanliga': 'http://www.espn.in/soccer/table/_/league/swe.1',
    'romanian first division': 'http://www.espn.in/soccer/table/_/league/rou.1',
    'israeli premier league': 'http://www.espn.in/soccer/table/_/league/isr.1',
    'maltese premier league': 'http://www.espn.in/soccer/table/_/league/mlt.1',
    'french ligue 2': 'http://www.espn.in/soccer/table/_/league/fra.2',
    'dutch eerste divisie': 'http://www.espn.in/soccer/table/_/league/ned.2',
    u'primera división de argentina': 'http://www.espn.in/soccer/table/_/league/arg.1',
    'nacional b de argentina': 'http://www.espn.in/soccer/table/_/league/arg.2',
    'primera division b de argentina': 'http://www.espn.in/soccer/table/_/league/arg.3',
    'argentina primera c metropolitana': 'http://www.espn.in/soccer/table/_/league/arg.4',
    'primera division d de argentina': 'http://www.espn.in/soccer/table/_/league/arg.5',
    'brazil serie a': 'http://www.espn.in/soccer/table/_/league/bra.1',
    'brazil serie b': 'http://www.espn.in/soccer/table/_/league/bra.2',
    'brazil campeonato mineiro': 'http://www.espn.in/soccer/table/_/league/bra.camp.mineiro',
    'brazil: campeonato gaucho': 'http://www.espn.in/soccer/table/_/league/bra.camp.gaucho',
    u'fútbol profesional colombiano': 'http://www.espn.in/soccer/table/_/league/col.1',
    'primera division de chile': 'http://www.espn.in/soccer/table/_/league/chi.1',
    'ecuador serie a': 'http://www.espn.in/soccer/table/_/league/ecu.1',
    'primera division de paraguay': 'http://www.espn.in/soccer/table/_/league/par.1',
    'primera division de uruguay': 'http://www.espn.in/soccer/table/_/league/uru.1',
    'primera profesional de peru': 'http://www.espn.in/soccer/table/_/league/per.1',
    'primera division venezuela': 'http://www.espn.in/soccer/table/_/league/ven.1',
    'bolivia liga de futbol': 'http://www.espn.in/soccer/table/_/league/bol.1',
    'guatemala primera division': 'http://www.espn.in/soccer/table/_/league/gua.1',
    'primera division de honduras': 'http://www.espn.in/soccer/table/_/league/hon.1',
    u'primera división de el salvador': 'http://www.espn.in/soccer/table/_/league/slv.1',
    'north american soccer league': 'http://www.espn.in/soccer/table/_/league/usa.nasl',
    'nwsl womens league': 'http://www.espn.in/soccer/table/_/league/usa.nwsl',
    'australian a-league': 'http://www.espn.in/soccer/table/_/league/aus.1',
    'japanese j league': 'http://www.espn.in/soccer/table/_/league/jpn.1',
    'indonesia liga 1': 'http://www.espn.in/soccer/table/_/league/idn.1',
    'malaysian super league': 'http://www.espn.in/soccer/table/_/league/mys.1',
    'singapore s-league': 'http://www.espn.in/soccer/table/_/league/sgp.1',
    'thai premier league': 'http://www.espn.in/soccer/table/_/league/tha.1',
    'south african premiership': 'http://www.espn.in/soccer/table/_/league/rsa.1',
    'south african national first division': 'http://www.espn.in/soccer/table/_/league/rsa.2',
    'nigeria professional league': 'http://www.espn.in/soccer/table/_/league/nga.1',
    'ghana premier league': 'http://www.espn.in/soccer/table/_/league/gha.1',
    'kenyan premier league': 'http://www.espn.in/soccer/table/_/league/ken.1',
    'uganda super league': 'http://www.espn.in/soccer/table/_/league/uga.1',
    'zambian league': 'http://www.espn.in/soccer/table/_/league/zam.1',
    'premier soccer league': 'http://www.espn.in/soccer/table/_/league/zim.1',
    'brazilian campeonato carioca': 'http://www.espn.in/soccer/table/_/league/bra.camp.carioca'
}


session=Session()
def fetch_url(url):
    req = session.get(url)
    if req.status_code != 200:
        print("Unable to download: {}: status_code: {}".format(url, req.status_code))
    else:
        print("url {0} working fine".format(url))
    return True


for url in empty_urls:
    fetch_url(empty_urls[url])
